[package]
name = "metrix"
version = "0.4.0"
authors = ["Christian Douven <chridou@users.noreply.github.com>"]
readme = "README.md"
license = "Apache-2.0/MIT"
description = "metrics for application monitoring"
documentation = "https://docs.rs/metrix"
homepage = "https://github.com/chridou/metrix"
repository = "https://github.com/chridou/metrix"
keywords = ["metrics", "monitoring"]

[dependencies]
exponential-decay-histogram = "0.1.0"
metrics = "0.2.0"
json = "0.11.0"
